(function attachCommunicationService(root, factory) {
  const api=factory(); if(typeof module!=='undefined'&&module.exports)module.exports=api; root.OG_COMMUNICATION_SERVICE=api;
}(typeof globalThis!=='undefined'?globalThis:this,function createCommunicationService(){
  'use strict';
  const TEMPLATES=Object.freeze([
    {templateId:'wa_first',name:'Primeiro contato',channel:'whatsapp',objective:'FIRST_CONTACT',version:1,content:'Olá, {{first_name}}! Aqui é o {{seller}}, da Olho de Gato. Gostaria de entender como a {{company}} trabalha hoje o controle dos pneus da frota. Qual horário fica melhor para uma conversa rápida?',variables:['first_name','seller','company'],status:'active'},
    {templateId:'wa_no_answer',name:'Não atendeu',channel:'whatsapp',objective:'NO_ANSWER',version:1,content:'Olá, {{first_name}}! Aqui é o {{seller}}, da Olho de Gato. Tentei falar com você sobre a operação da {{company}}. Qual horário fica melhor para conversarmos?',variables:['first_name','seller','company'],status:'active'},
    {templateId:'wa_after_call',name:'Pós-ligação',channel:'whatsapp',objective:'AFTER_CALL',version:1,content:'Olá, {{first_name}}! Obrigado pela conversa. Conforme combinamos, {{next_action}}.',variables:['first_name','next_action'],status:'active'},
    {templateId:'wa_presentation',name:'Apresentação',channel:'whatsapp',objective:'PRESENTATION',version:1,content:'Olá, {{first_name}}! Separei a apresentação da Olho de Gato para a {{company}}. Depois que analisar, podemos alinhar o próximo passo.',variables:['first_name','company'],status:'active'},
    {templateId:'wa_quote',name:'Orçamento',channel:'whatsapp',objective:'QUOTE',version:1,content:'Olá, {{first_name}}! Preparei o orçamento solicitado para a {{company}}. Revise os dados e me diga se deseja ajustar algum ponto.',variables:['first_name','company'],status:'active'},
    {templateId:'wa_follow',name:'Follow-up',channel:'whatsapp',objective:'FOLLOW_UP',version:1,content:'Olá, {{first_name}}! Retomando nosso contato sobre {{next_action}}. Posso ajudar em alguma dúvida para avançarmos?',variables:['first_name','next_action'],status:'active'},
    {templateId:'wa_recovery',name:'Recuperar negociação',channel:'whatsapp',objective:'RECOVERY',version:1,content:'Olá, {{first_name}}! Quero retomar nossa conversa com objetividade. O que precisa estar claro para avaliarmos o próximo passo na {{company}}?',variables:['first_name','company'],status:'active'},
    {templateId:'wa_price',name:'Objeção de preço',channel:'whatsapp',objective:'PRICE_TOO_HIGH',version:1,content:'Entendo que o investimento precisa fazer sentido. Antes de discutir condição, posso confirmar quais custos da operação mais pesam hoje para avaliarmos valor com dados reais?',variables:[],status:'active'},
    {templateId:'wa_cost',name:'Redução de custos',channel:'whatsapp',objective:'COST_REDUCTION',version:1,content:'Entendo a prioridade de reduzir despesas. Para avaliar se existe um investimento capaz de reduzir custo operacional, precisamos usar os dados reais da frota. Podemos levantar essas informações?',variables:[],status:'active'},
    {templateId:'wa_referral',name:'Indicação',channel:'whatsapp',objective:'REFERRAL',version:1,content:'Olá, {{first_name}}! Quem na sua rede também cuida de frota e poderia se beneficiar de uma conversa técnica e objetiva sobre gestão dos pneus?',variables:['first_name'],status:'active'},
    {templateId:'wa_after_sales',name:'Pós-venda',channel:'whatsapp',objective:'AFTER_SALES',version:1,content:'Olá, {{first_name}}! Como está a experiência da {{company}} até aqui? Quero registrar o que está funcionando e qualquer ponto que precise de suporte.',variables:['first_name','company'],status:'active'},
    {templateId:'email_quote',name:'Orçamento formal',channel:'email',objective:'QUOTE',version:1,subject:'Orçamento Olho de Gato para {{company}}',content:'Olá, {{contact_name}}.\n\nConforme conversamos, segue o orçamento preparado para a {{company}}. Os valores e condições devem ser conferidos no documento vigente antes do envio.\n\nPróximo passo: {{next_action}}.\n\nAtenciosamente,\n{{seller}}',variables:['contact_name','company','next_action','seller'],status:'active'},
    {templateId:'email_follow',name:'Follow-up profissional',channel:'email',objective:'FOLLOW_UP',version:1,subject:'Próximo passo com a {{company}}',content:'Olá, {{contact_name}}.\n\nRetomo nosso contato para confirmar se existe alguma dúvida técnica ou comercial pendente. Podemos alinhar {{next_action}}?\n\nAtenciosamente,\n{{seller}}',variables:['contact_name','next_action','seller'],status:'active'}
  ]);
  function templates(channel,objective){return TEMPLATES.filter(t=>t.channel===channel&&(!objective||t.objective===objective));}
  function render(template,variables={}){const missing=[];const fill=text=>String(text||'').replace(/{{([a-z0-9_]+)}}/gi,(_,key)=>{const value=String(variables[key]||'').trim();if(!value)missing.push(key);return value;}).replace(/\s+([.,!?])/g,'$1').replace(/\n{3,}/g,'\n\n');return{body:fill(template.content),subject:fill(template.subject),missing:[...new Set(missing)],template};}
  function record(input={}){return{communicationId:input.communicationId||`COM-${Date.now()}`,companyId:input.companyId||'',contactId:input.contactId||'',opportunityId:input.opportunityId||'',channel:input.channel||'',objective:input.objective||'',templateId:input.templateId||'',aiUsed:Boolean(input.aiUsed),knowledge_ids_used:[...(input.knowledge_ids_used||[])],createdAt:input.createdAt||new Date().toISOString(),createdBy:input.createdBy||'local-user',status:input.status||'draft',subject:input.subject||'',body:input.body||''};}
  return{TEMPLATES,templates,render,record};
}));
