import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const { view } = require('../apps/sistema-og/components/technical-workspace.js');
const app = fs.readFileSync(new URL('../apps/sistema-og/app.js', import.meta.url), 'utf8');
const engine = app.slice(app.indexOf('  function resolveVehicleSupports('), app.indexOf('  function renderConsultantEngine('));
const dataContext = vm.createContext({});
vm.runInContext(fs.readFileSync(new URL('../apps/sistema-og/data.js', import.meta.url), 'utf8'), dataContext);
const data = JSON.parse(vm.runInContext('JSON.stringify(OG_DATA)', dataContext));
const engineContext = vm.createContext({});
vm.runInContext(engine, engineContext);
let calls = 0;
const build = (...args) => { calls++; return engineContext.buildConsolidatedVehiclePieces(...args); };
const draft = { selectedVehicleId:'', answers:{}, libras:'', qty:1, includeDianteira:true, manualItems:null, manualConfirmed:false };
assert.equal(view(draft,data,build).items.length,0);
assert.equal(calls,0, 'Empty context must never invoke a permissive default mapping');
draft.selectedVehicleId = '3_4';
draft.libras = 110;
assert.equal(view(draft,data,build).state,'validate');
assert.equal(calls,0, 'Missing required answers must never invoke the engine');
draft.answers = {wheel_size:'19',has_truck_3_4:'nao'};
const valid = view(draft,data,build);
assert.equal(valid.ready,true);
assert.deepEqual(Object.fromEntries(valid.items.map(item => [item.code,item.qty])), {'EQ-110':2,'EQ-1155':2,'EQ-1040':2,'EQ-1043':2,'EQ-110D':2,'EQ-1340':2,'EQ-1041':2});
const beforeInvalid = calls;
for (const patch of [{selectedVehicleId:'not-known'},{qty:0},{qty:1.5},{libras:999},{answers:{wheel_size:'unknown',has_truck_3_4:'nao'}}]) {
  const result = view({...draft,...patch},data,build);
  assert.equal(result.ready,false);
  assert.equal(result.items.length,0);
}
assert.equal(calls,beforeInvalid, 'Invalid inputs must not invoke the engine');
const conditional = {...draft,selectedVehicleId:'toco_4x2',answers:{brand:'mb'}};
assert.equal(view(conditional,data,build).state,'validate','Visible conditional year must be answered explicitly');
assert.equal(calls,beforeInvalid);
const manual = {...draft,manualItems:[{code:'EQ-700',qty:3,customPrice:null}],manualConfirmed:true};
assert.equal(view(manual,data,build).ready,true);
const recalculated = view({...manual,libras:120},data,build);
assert.deepEqual(recalculated.items,manual.manualItems,'Recalculation must preserve explicit manual composition');
assert.notDeepEqual(recalculated.baseItems,manual.manualItems,'Automatic base remains separate from manual result');
assert.equal(view({...manual,manualConfirmed:false},data,build).ready,false);
assert.equal(view({...manual,manualItems:[]},data,build).items.length,0,'Removing all items must not resurrect automatic pieces');
assert.equal(view({...manual,manualItems:[{code:'fabricated',qty:1}]},data,build).ready,false);
const failed = view(draft,data,() => {throw new Error('QA engine failure');});
assert.equal(failed.state,'error');
assert.deepEqual(failed.items,[]);
assert.equal(failed.ready,false);
console.log('Technical workspace canonical input/conditional/unknown/quantity/manual/error contracts: PASS');
