import assert from 'node:assert/strict';
import fs from 'node:fs';
import worker from '../cloudflare/worker.mjs';
const app=fs.readFileSync('apps/sistema-og/app.js','utf8');
const server=fs.readFileSync('apps/sistema-og/server.mjs','utf8');
const sw=fs.readFileSync('apps/sistema-og/service-worker.js','utf8');
const syncBridge=fs.readFileSync('apps/sistema-og/services/sync-bridge-service.js','utf8');
const hosted=fs.readFileSync('scripts/start-og-hosted.mjs','utf8');
const proposalStore=fs.readFileSync('apps/sistema-og/server-proposal-store.cjs','utf8');
assert.doesNotMatch(app,/localStorage\.getItem\('og_cloud_access_token'/);
assert.match(app,/sessionStorage\.getItem\('og_cloud_access_token'/);
assert.match(app,/currentToken && currentToken !== usedToken/,'401 concorrente não deve apagar um PIN novo já informado');
assert.match(app,/response = await request\(currentToken\)/,'401 concorrente deve tentar o PIN de sessão mais recente antes de pedir de novo');
assert.doesNotMatch(app,/toast\.innerHTML\s*=/,'toast não pode interpolar mensagem dinâmica como HTML');
assert.match(app,/copy\.textContent = String\(msg \|\| ''\)/,'toast deve tratar mensagens dinâmicas como texto');
assert.doesNotMatch(app,/forceMerge:true|\/api\/state\?merge=1/);
assert.doesNotMatch(sw,/forceMerge:\s*true/);
assert.doesNotMatch(syncBridge,/Authorization|Bearer|og_cloud_access_token/,'Sync Bridge não deve persistir credenciais');
assert.doesNotMatch(sw,/fetch\(pending\.url/,'Service Worker não deve enviar outbox sem sessão do foreground');
assert.match(sw,/url\.pathname\.startsWith\('\/p\/'\)/,'Service Worker deve ignorar páginas públicas de proposta');
assert.match(sw,/url\.pathname\.startsWith\('\/public-api\/'\)/,'Service Worker deve ignorar eventos públicos de proposta');
assert.match(proposalStore,/createHash\('sha256'\)/,'Token público deve ser persistido somente como hash');
assert.match(server,/Content-Security-Policy/,'Página pública de proposta precisa de CSP');
assert.match(server,/X-Robots-Tag/,'Página pública de proposta precisa bloquear indexação');
assert.match(server,/readBody\(req, 10_000\)/,'Endpoint público deve limitar payload');
assert.doesNotMatch(app,/publicToken\s*:\s*result\./,'Token público não pode ser copiado para estado persistente do browser');
assert.match(server,/process\.env\.OG_HOST \|\| '127\.0\.0\.1'/);
assert.match(server,/OG_LOCAL_ACCESS_TOKEN/);
assert.match(hosted,/OG_LOCAL_ACCESS_TOKEN \|\| process\.env\.OG_ACCESS_TOKEN/,'Hosted runtime deve aceitar segredo dedicado sem hardcode');
assert.match(hosted,/token\.length < 16/,'Hosted runtime deve manter segredo principal forte');
assert.match(hosted,/OG_ACCESS_PIN/,'Hosted runtime deve aceitar PIN separado do segredo principal');
assert.match(server,/OG_LOCAL_ACCESS_PIN/,'Servidor deve aceitar PIN hospedado separado');
assert.match(hosted,/OG_HOST = process\.env\.OG_HOST \|\| '0\.0\.0\.0'/,'Hosted runtime deve bindar todas interfaces somente pelo entrypoint hospedado');
const pkg=JSON.parse(fs.readFileSync('package.json','utf8'));
assert.equal(pkg.scripts.start,'npm run og:start:hosted','Railway novo deve detectar o start padrão sem Config as Code legado');
assert.doesNotMatch(fs.readdirSync('.').join('\n'),/^railway\.json$/m,'railway.json legado não deve voltar ao root');
const store=new Map();
const env={OG_ACCESS_TOKEN:'0123456789abcdef',OG_DATA:{get:async(k,type)=>{const v=store.get(k);return type==='json'&&v?JSON.parse(v):v||null;},put:async(k,v)=>store.set(k,v)},ASSETS:{fetch:async()=>new Response('asset')}};
let response=await worker.fetch(new Request('https://example.test/api/state'),env);assert.equal(response.status,401);
const headers={authorization:'Bearer 0123456789abcdef','content-type':'application/json'};
response=await worker.fetch(new Request('https://example.test/api/state',{method:'PUT',headers,body:JSON.stringify({revision:0,leads:[],history:[],operations:null})}),env);assert.equal(response.status,200);
response=await worker.fetch(new Request('https://example.test/api/state',{method:'PUT',headers,body:JSON.stringify({revision:0,leads:[],history:[],operations:null,forceMerge:true})}),env);assert.equal(response.status,409);
response=await worker.fetch(new Request('https://example.test/api/state',{method:'PUT',headers,body:'{"revision":1,"leads":"bad","history":[]}'}),env);assert.equal(response.status,400);
const oversized=JSON.stringify({revision:0,leads:[],history:[],padding:'x'.repeat(5_000_001)});
const oversizedBytes=new TextEncoder().encode(oversized);
const noLengthHeaders=new Headers({authorization:'Bearer 0123456789abcdef','content-type':'application/json'});
response=await worker.fetch(new Request('https://example.test/api/state',{method:'PUT',headers:noLengthHeaders,body:oversizedBytes}),env);assert.equal(response.status,413);
const forgedLengthHeaders=new Headers({authorization:'Bearer 0123456789abcdef','content-type':'application/json','content-length':'1'});
response=await worker.fetch(new Request('https://example.test/api/state',{method:'PUT',headers:forgedLengthHeaders,body:oversizedBytes}),env);assert.equal(response.status,413);
const temp={OG_TEMP_MODE:'true',OG_ACCESS_TOKEN:'0123456789abcdef',ASSETS:env.ASSETS};
response=await worker.fetch(new Request('https://example.test/api/state',{method:'PUT',headers,body:JSON.stringify({revision:0,leads:[],history:[]})}),temp);assert.equal(response.status,503);
console.log('Security baseline tests: PASS');
