import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
const require=createRequire(import.meta.url);
const gateway=require('../apps/sistema-og/server-sales-execution-gateway.cjs');
assert.equal(gateway.cfg({}).enabled,false);
assert.equal(gateway.cfg({OG_SUPABASE_URL:'https://x.supabase.co',OG_SUPABASE_SERVICE_ROLE_KEY:'secret'}).enabled,true);
const result=await gateway.listLists({});
assert.equal(result.status,503);
assert.equal(result.configured,false);
console.log('sales-execution-gateway: safe disabled mode ok');
