import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const safety=require('../apps/sistema-og/services/data-safety-service.js');
const model=require('../apps/sistema-og/operations-model.js');
const original={leads:[{id:'L-RESTORE-1',empresa:'Fixture sintética',updatedAt:'2026-09-25T12:00:00.000Z'}],history:[{id:'H-RESTORE-1',date:'2026-09-25T12:00:00.000Z',action:'fixture'}],operations:model.createEmptyOperations('2026-09-25T12:00:00.000Z')};
original.operations.activityEvents=[{id:'E-RESTORE-1',type:'test.fixture',at:'2026-09-25T12:00:00.000Z'}];
const backup=safety.createBackup(original,{source:'synthetic-restore-drill',revision:7});
const portable=JSON.parse(JSON.stringify(backup));
const validation=safety.validateBackup(portable);
assert.equal(validation.valid,true);assert.deepEqual(validation.counts,{leads:1,history:1,events:1});
const empty={leads:[],history:[],operations:model.createEmptyOperations('2026-09-25T12:01:00.000Z')};
const restored=safety.mergeBackup(empty,portable,model);
assert.deepEqual(restored.leads.map(x=>x.id),['L-RESTORE-1']);
assert.deepEqual(restored.history.map(x=>x.id),['H-RESTORE-1']);
assert.ok(restored.operations.activityEvents.some(x=>x.id==='E-RESTORE-1'));
const secondBackup=safety.createBackup(restored,{source:'post-restore-healthcheck',revision:8});
assert.equal(safety.validateBackup(secondBackup).valid,true);
assert.deepEqual(safety.validateBackup(secondBackup).counts,validation.counts);
console.log('Backup/restore drill: PASS (synthetic fixture, counts and IDs reconciled)');
