import assert from 'node:assert/strict';
import fs from 'node:fs';
import worker from '../cloudflare/worker.mjs';
const app=fs.readFileSync('apps/sistema-og/app.js','utf8');
const server=fs.readFileSync('apps/sistema-og/server.mjs','utf8');
const sw=fs.readFileSync('apps/sistema-og/service-worker.js','utf8');
assert.doesNotMatch(app,/localStorage\.getItem\('og_cloud_access_token'/);
assert.match(app,/sessionStorage\.getItem\('og_cloud_access_token'/);
assert.doesNotMatch(app,/forceMerge:true|\/api\/state\?merge=1/);
assert.doesNotMatch(sw,/forceMerge:\s*true/);
assert.match(server,/process\.env\.OG_HOST \|\| '127\.0\.0\.1'/);
assert.match(server,/OG_LOCAL_ACCESS_TOKEN/);
const store=new Map();
const env={OG_ACCESS_TOKEN:'0123456789abcdef',OG_DATA:{get:async(k,type)=>{const v=store.get(k);return type==='json'&&v?JSON.parse(v):v||null;},put:async(k,v)=>store.set(k,v)},ASSETS:{fetch:async()=>new Response('asset')}};
let response=await worker.fetch(new Request('https://example.test/api/state'),env);assert.equal(response.status,401);
const headers={authorization:'Bearer 0123456789abcdef','content-type':'application/json'};
response=await worker.fetch(new Request('https://example.test/api/state',{method:'PUT',headers,body:JSON.stringify({revision:0,leads:[],history:[],operations:null})}),env);assert.equal(response.status,200);
response=await worker.fetch(new Request('https://example.test/api/state',{method:'PUT',headers,body:JSON.stringify({revision:0,leads:[],history:[],operations:null,forceMerge:true})}),env);assert.equal(response.status,409);
response=await worker.fetch(new Request('https://example.test/api/state',{method:'PUT',headers,body:'{"revision":1,"leads":"bad","history":[]}'}),env);assert.equal(response.status,400);
const oversized=JSON.stringify({revision:0,leads:[],history:[],padding:'x'.repeat(5_000_001)});
const oversizedBytes=new TextEncoder().encode(oversized);
const noLengthHeaders=new Headers({authorization:'Bearer 0123456789abcdef','content-type':'application/json'});
response=await worker.fetch(new Request('https://example.test/api/state',{method:'PUT',headers:noLengthHeaders,body:oversizedBytes}),env);assert.equal(response.status,413);
const forgedLengthHeaders=new Headers({authorization:'Bearer 0123456789abcdef','content-type':'application/json','content-length':'1'});
response=await worker.fetch(new Request('https://example.test/api/state',{method:'PUT',headers:forgedLengthHeaders,body:oversizedBytes}),env);assert.equal(response.status,413);
const temp={OG_TEMP_MODE:'true',OG_ACCESS_TOKEN:'0123456789abcdef',ASSETS:env.ASSETS};
response=await worker.fetch(new Request('https://example.test/api/state',{method:'PUT',headers,body:JSON.stringify({revision:0,leads:[],history:[]})}),temp);assert.equal(response.status,503);
console.log('Security baseline tests: PASS');
