import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {createRequire} from 'node:module';
const require = createRequire(import.meta.url);
const map = require('../apps/sistema-og/components/technical-application-map.js');
const {view} = require('../apps/sistema-og/components/technical-workspace.js');
const app = fs.readFileSync(new URL('../apps/sistema-og/app.js',import.meta.url),'utf8');
const context = vm.createContext({});
vm.runInContext(fs.readFileSync(new URL('../apps/sistema-og/data.js',import.meta.url),'utf8'),context);
const data = JSON.parse(vm.runInContext('JSON.stringify(OG_DATA)',context));
vm.runInContext(app.slice(app.indexOf('  function resolveVehicleSupports('),app.indexOf('  function renderConsultantEngine(')),context);
const build = (...args) => context.buildConsolidatedVehiclePieces(...args);
const plain = value => JSON.parse(JSON.stringify(value));
const sum = rows => rows.reduce((result,row) => { result[row.code]=(result[row.code]||0)+row.qty;return result; },{});
const draft = {selectedVehicleId:'trucado_carreta3',answers:{brand:'volvo',has_reduction:'nao'},libras:120,qty:2,includeDianteira:true,manualItems:null};
const computed = view(draft,data,build);
const split = map.model({...computed,draft,data});
assert.deepEqual(sum(split.rows),sum(computed.items),'Split quantities exactly equal the canonical consolidated composition');
const sameCode = split.rows.filter(row => row.code === 'EQ-1135');
assert.deepEqual(plain(sameCode.map(row => [row.scope,row.position,row.qty])),[['cavalo','truck',2],['carreta','carreta',6]],'Same code has distinct origins; never always-trailer');
assert.ok(split.rows.filter(row => ['dianteiro','tracao'].includes(row.position)).every(row => row.scope === 'cavalo'));
assert.ok(split.rows.every(row => row.status === 'runtime' && row.path.includes(`Regra do motor: ${computed.rule.id}`)));
assert.ok(split.rows.filter(row => row.scope === 'carreta').every(row => !row.path.some(step => step.includes('Volvo'))),'Trailer path does not invent dependence on tractor brand');
assert.ok(map.html(split,{multiplier:2}).includes('data-map-position="truck"'));
assert.deepEqual(map.model({items:[{code:'EQ-1135',qty:2}],data}).rows.map(row => [row.scope,row.status]),[['validar','validate']]);
const manual = {...draft,manualItems:[{code:'EQ-1135',qty:5,applicationScope:'cavalo'}],manualConfirmed:true};
const manualResult = map.model({...view(manual,data,build),draft:manual,data});
assert.equal(manualResult.rows[0].scope,'cavalo');
assert.equal(manualResult.rows[0].origin,'manual');
assert.equal(manualResult.rows[0].position,'validar');
assert.equal(manualResult.rows[0].status,'validate','User classification is not certified installation');
const unclassified = {...manual,manualItems:[{code:'EQ-1135',qty:5}]};
assert.equal(map.model({...view(unclassified,data,build),draft:unclassified,data}).rows[0].scope,'validar');
const trailer = {...draft,applicationScope:'carreta',answers:{},queryMode:true};
const trailerView = view(trailer,data,build);
assert.equal(trailerView.ready,true,'Independent trailer branches do not require unrelated tractor answers');
assert.equal(trailerView.questions.length,0);
assert.ok(trailerView.applicationEntries.every(row => row.position === 'carreta'));
assert.deepEqual(sum(trailerView.items),{'EQ-120':6,'EQ-1135':6,'EQ-1040':6,'EQ-1043':6});
assert.ok(map.model({...trailerView,draft:trailer,data}).rows.every(row => row.scope === 'carreta'));
assert.equal(view({...trailer,selectedVehicleId:'toco_4x2'},data,build).ready,false,'No fabricated standalone trailer mapping');
assert.equal(view({...draft,applicationScope:'fabricated'},data,build).ready,false);
assert.ok(view({...draft,applicationScope:'cavalo'},data,build).applicationEntries.every(row => row.position !== 'carreta'));
const snapshots = plain({client:{empresa:'Empresa 0000'},vehicles:[{id:'FAKE-VEH-0000',items:computed.items,technicalContext:draft},{id:'FAKE-VEH-0001',items:manual.manualItems,technicalContext:manual}],extraItems:[]});
assert.equal(snapshots.vehicles[1].items[0].applicationScope,'cavalo');
assert.deepEqual(plain(map.model({...view(snapshots.vehicles[0].technicalContext,data,build),draft:snapshots.vehicles[0].technicalContext,data}).rows),plain(split.rows));
assert.equal(map.model({...view(snapshots.vehicles[1].technicalContext,data,build),draft:snapshots.vehicles[1].technicalContext,data}).rows[0].scope,'cavalo');
assert.ok(Buffer.byteLength(JSON.stringify(snapshots))<10_000,'Minimal reconstructible composition; no global state/history copied');
assert.ok(!['leads','history','operations','state'].some(key => Object.hasOwn(snapshots,key)));
for (const rule of data.vehicleConsultantRules) {
  const answers = {};
  for (const question of rule.questions) if (!question.showIf || Object.entries(question.showIf).every(([key,val])=>answers[key]===val)) answers[question.id]=question.options[0].value;
  for (const libras of [110,115,120]) for (const includeDianteira of [true,false]) {
    const result = build(rule.id,answers,libras,includeDianteira);
    assert.deepEqual(sum(result.resultList),sum(result.applicationEntries),'Metadata is emitted by the same addPiece calls, without changing quantities');
    assert.deepEqual(sum([...build(rule.id,answers,libras,includeDianteira,'cavalo').resultList,...build(rule.id,answers,libras,includeDianteira,'carreta').resultList]),sum(result.resultList),'Disjoint canonical scope projection reconstructs default quantities');
  }
}
console.log('Technical map: context/position provenance, same-code split, canonical query, manual VALIDAR, snapshot reconstruction and all-rule quantities PASS');
