import assert from 'node:assert/strict';
import fs from 'node:fs';

const migration = fs.readFileSync('supabase/migrations/20261003120000_add_canonical_account_assets.sql', 'utf8');
const adr = fs.readFileSync('docs/architecture/ADR-ASSET-01-CANONICAL-VISUAL-MEMORY.md', 'utf8');
const server = fs.readFileSync('apps/sistema-og/server.mjs', 'utf8');

assert.match(migration, /create table if not exists public\.assets\s*\(/i);
assert.match(migration, /create table if not exists public\.asset_versions\s*\(/i);
assert.match(migration, /create table if not exists public\.asset_links\s*\(/i);
assert.match(migration, /company_id uuid not null references public\.companies\(id\) on delete restrict/i);
assert.match(migration, /asset_id uuid not null references public\.assets\(id\) on delete cascade/i);
assert.match(migration, /unique \(asset_id, version_number\)/i);
assert.match(migration, /unique \(storage_bucket, storage_path\)/i);
assert.match(migration, /where is_primary = true and status = 'ACTIVE'/i);
assert.match(migration, /storage_bucket text not null default 'account-assets'/i);
assert.match(migration, /media_kind text not null/i);
assert.match(migration, /business_category text not null/i);
assert.match(migration, /source_type text not null/i);
assert.match(migration, /visibility_class text not null/i);
assert.match(migration, /sensitivity_level text not null/i);
assert.match(migration, /usage_policy text not null/i);
assert.match(migration, /current_version_id uuid/i);
assert.match(migration, /references public\.asset_versions\(id\)/i);
assert.match(migration, /assert_asset_current_version_ownership/i);
assert.match(migration, /assets_current_version_ownership_guard/i);
assert.match(migration, /v\.asset_id = new\.id/i);
assert.match(migration, /num_nonnulls\(contact_id, opportunity_id, proposal_id, activity_id\) = 1/i);
assert.match(migration, /proposal_id is null or pinned_version_id is not null/i);
assert.match(migration, /assert_asset_link_integrity/i);
assert.match(migration, /target must belong to the same canonical company/i);
assert.match(migration, /alter table public\.asset_links enable row level security/i);
assert.match(migration, /revoke all on public\.asset_links from anon, authenticated/i);
const categoryBlock = migration.match(/check \(business_category in \(\s*([\s\S]*?)\s*\)\),/i)?.[1] || '';
assert.doesNotMatch(categoryBlock, /'WHATSAPP'/i, 'WhatsApp deve ser origem, não categoria comercial');
assert.match(categoryBlock, /'CONVERSATION'/i, 'Conversa deve ser categoria comercial válida');
assert.doesNotMatch(migration, /insert into storage\.buckets|update storage\.buckets|delete from storage\.buckets/i, 'Storage deve ser provisionado pela API');
assert.match(migration, /alter table public\.assets enable row level security/i);
assert.match(migration, /alter table public\.asset_versions enable row level security/i);
assert.match(migration, /revoke all on public\.assets from anon, authenticated/i);
assert.match(migration, /revoke all on public\.asset_versions from anon, authenticated/i);
assert.doesNotMatch(migration, /create policy/i, 'ASSET-01 não libera browser antes de Auth\/Organization');
assert.doesNotMatch(migration, /organization_id/i, 'ASSET-01 não simula multitenancy somente em Assets');
assert.doesNotMatch(migration, /alter table public\.company_brand_assets/i);
assert.doesNotMatch(migration, /alter table public\.proposal_artifacts/i);
assert.match(adr, /gateway-only/i);
assert.match(adr, /company_brand_assets/i);
assert.match(adr, /proposal_artifacts/i);
assert.match(adr, /Organization não será simulada apenas em Assets/i);
assert.match(adr, /TERR-01A/i);
assert.match(adr, /PUBLIC_SOURCE.*nunca significa/is);
assert.match(adr, /WhatsApp é origem, não categoria comercial/i);
assert.match(server, /\/api\/assets\/upload/);
assert.match(server, /server-asset-gateway\.cjs/);

console.log('Asset domain contract tests: PASS');
