import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
const require=createRequire(import.meta.url);
const service=require('../apps/sistema-og/services/spreadsheet-import-service.js');
const sheets={};
for(const name of service.CRM_SHEETS)sheets[name]=name==='📋 CRM'?[['meta'],['meta'],['meta'],['meta'],['meta'],['meta'],service.CRM_HEADERS,['0012','Rodolog','04499999999','novo','Morno','Ligar amanhã','','Alta','','Nota humana','','Prospect','Lista','WhatsApp','','Observação protegida','','12345678000190','','PJ','Maringá / PR','João','1']]:[['fixture']];
const wb={SheetNames:service.CRM_SHEETS.slice(),sheets};
assert.equal(service.validateWorkbook(wb).valid,true);
const rows=service.readCrmRows(wb);assert.equal(rows[0].externalCode,'0012');assert.equal(rows[0].phone,'04499999999');
let preview=service.preview(rows,[]);assert.equal(preview[0].status,'NEW');
const leads=[{id:'L1',internalCode:'0012',empresa:'Rodolog',telefone:'04499999999',status:'novo',nextAction:'Ligar amanhã',priority:'Alta',observacoes:'Texto diferente'}];
preview=service.preview(rows,leads);assert.equal(preview[0].status,'CONFLICT');assert.equal(preview[0].matchKey,'external_code');
assert.ok(preview[0].changes.some(item=>item.field==='notes'&&item.protected));
const kept=service.applyPreview(preview,leads,{'8':{fields:{notes:'keep'}}},{now:'2026-09-24T12:00:00.000Z'});assert.equal(kept.applied,0);assert.equal(kept.leads[0].observacoes,'Texto diferente');
const merged=service.applyPreview(preview,leads,{'8':{fields:{notes:'append'}}},{now:'2026-09-24T12:00:00.000Z'});assert.equal(merged.applied,1);assert.match(merged.leads[0].observacoes,/Observação protegida/);
const created=service.applyPreview(service.preview(rows,[]),[],{'8':{action:'import',fields:{}}},{now:'2026-09-24T12:00:00.000Z',idFactory:()=> 'L2'});assert.equal(created.leads[0].id,'L2');
assert.equal(service.preview(rows,created.leads)[0].status,'UNCHANGED');
assert.throws(()=>service.preflightFile({name:'dados.xls',size:100}),/\.xlsx/);
assert.throws(()=>service.preflightFile({name:'dados.xlsx',size:5_000_001}),/5 MB/);
assert.throws(()=>service.validateSanitizedWorkbook({SheetNames:['x'],sheets:{x:'bad'}}),/limite de linhas/);
assert.throws(()=>service.validateSanitizedWorkbook({SheetNames:['x'],sheets:{x:[["x".repeat(10_001)]]}}),/limite de texto/);
assert.throws(()=>service.validateSanitizedWorkbook(null),/inválido/);
assert.equal(service.IMPORT_LIMITS.maxCells,100000);
console.log('Spreadsheet import tests: PASS');
