import assert from 'node:assert/strict';
import fs from 'node:fs';
import { createRequire } from 'node:module';
const require=createRequire(import.meta.url);
const communication=require('../apps/sistema-og/services/communication-service.js');
const selector=require('../apps/sistema-og/services/knowledge-selector.js');
const prompts=require('../apps/sistema-og/services/call-ai-prompts.js');
const ai=require('../apps/sistema-og/services/ai-service.js');
const brain=JSON.parse(fs.readFileSync('apps/sistema-og/knowledge/og-sales-brain.json','utf8'));
assert.equal(brain.stats.jsonlRecords,13); assert.equal(brain.stats.docxRecords,0); assert.equal(brain.governance.docxIndexed,false);
assert.equal(new Set(brain.records.map(r=>r.knowledge_id)).size,13); assert.ok(brain.records.every(r=>r.status&&r.originalStatus&&r.confidence&&r.source));
assert.equal(brain.records.find(r=>r.knowledge_id==='OG-TIRE-002').status,'PENDENTE_VALIDACAO');
const price=selector.selectRecords(brain.records,{messagePurpose:'PRICE_TOO_HIGH',channel:'whatsapp',persona:'dono'},3);
assert.ok(price.some(r=>r.knowledge_id==='OG-PRICE-001')); assert.ok(price.length<=3);
const template=communication.templates('whatsapp','NO_ANSWER')[0];
const rendered=communication.render(template,{first_name:'João',seller:'Lucas',company:'Rodolog'});
assert.match(rendered.body,/João/); assert.equal(rendered.missing.length,0);
const missing=communication.render(communication.templates('email','QUOTE')[0],{contact_name:'Ana',seller:'Lucas'});
assert.ok(missing.missing.includes('company')); assert.ok(missing.missing.includes('next_action'));
const email=communication.record({companyId:'A',channel:'email',objective:'QUOTE',status:'draft'}); assert.equal(email.status,'draft'); assert.notEqual(email.status,'sent');
const unsafe=brain.records.filter(r=>r.knowledge_id==='OG-TIRE-002').map(selector.forPrompt);
const request=prompts.build('personalize_message',{company:{id:'A',name:'Rodolog'},contact:{name:'João'}},'Você terá +20% de vida útil.',unsafe);
const safe=await ai.generate(request); assert.doesNotMatch(safe.recommendedResponse,/Você terá \+?20%/i); assert.match(safe.recommendedResponse,/validado/i); assert.deepEqual(safe.knowledge_ids_used,['OG-TIRE-002']);
const cost=selector.selectRecords(brain.records,{messagePurpose:'COST_REDUCTION'},3); assert.ok(cost.some(r=>r.knowledge_id.startsWith('OG-FUEL')));
const policy=[]; assert.equal(policy.length?null:'ESCALATE_TO_HUMAN','ESCALATE_TO_HUMAN');
const roiData={tirePrice:null,dieselSpend:null}; assert.equal(Object.values(roiData).some(v=>!v)?'ASK_FOR_DATA':'READY','ASK_FOR_DATA');
const html=fs.readFileSync('apps/sistema-og/index.html','utf8'); const app=fs.readFileSync('apps/sistema-og/app.js','utf8');
assert.match(html,/tab-comunicacao/); assert.match(app,/Personalizar com IA|personalizeCommunication/); assert.match(app,/saveCommunication\('opened'\)/); assert.doesNotMatch(app,/saveCommunication\('sent'\)/);
console.log('Communication Center and Sales Brain checks: PASS');
