import fs from 'node:fs';
import assert from 'node:assert/strict';
const app=fs.readFileSync(new URL('../apps/sistema-og/app.js',import.meta.url),'utf8');
const html=fs.readFileSync(new URL('../apps/sistema-og/index.html',import.meta.url),'utf8');
const sw=fs.readFileSync(new URL('../apps/sistema-og/service-worker.js',import.meta.url),'utf8');

assert.ok(html.includes('services/sync-conflict-service.js'),'serviço de conflito não carregado');
assert.ok(html.includes('services/sync-bridge-service.js'),'Sync Bridge não carregado');
assert.ok(sw.includes("'/services/sync-conflict-service.js'"),'serviço de conflito fora do shell offline');
assert.ok(sw.includes("'/services/sync-bridge-service.js'"),'Sync Bridge fora do shell offline');
assert.ok(app.includes("OG_SYNC_CONFLICT.createConflict("),'409 deve criar snapshot de conflito');
assert.ok(app.includes("OG_SYNC_BRIDGE.saveConflict(conflict)"),'conflito deve persistir fora de sessionStorage');
assert.ok(app.includes("OG_SYNC_BRIDGE.queueState(currentSyncPayload(payload.revision))"),'falha de rede deve manter o estado local mais recente na outbox');
assert.ok(app.includes("async function flushQueuedState()"),'outbox deve ter flush autenticado no foreground');
assert.ok(app.includes("await restoreSyncRecovery();"),'recovery deve acontecer antes do pull inicial');
assert.ok(app.includes("readSmallMarker(SYNC_CONFLICT_MARKER) && !pendingSyncConflict()"),'marcador de conflito deve bloquear pull/sync');
assert.ok(app.includes("readSmallMarker(SYNC_REVIEW_MARKER) && !pendingSyncReview()"),'marcador de revisão deve bloquear pull/sync');
assert.ok(app.includes('serverSyncInFlight'),'escritas devem ser serializadas');
assert.ok(app.includes('serverSyncGeneration'),'edições durante request devem gerar novo envio');
assert.ok(app.includes("setTimeout(runScheduledServerSync, 120)"),'alteração concorrente deve ser reenfileirada sem auto-conflito');
assert.ok(app.includes("window.addEventListener('storage'"),'outras abas devem disparar recovery');
assert.ok(app.includes("resolved: true"),'limpeza resiliente deve usar tombstone antes de apagar recovery');
assert.ok(app.includes("if (pendingSyncConflict())"),'novo sync deve parar enquanto conflito estiver pendente');
assert.ok(app.includes('Ver divergências'),'UX de detalhes ausente');
assert.ok(app.includes('Preparar conciliação'),'UX de revisão ausente');
assert.ok(app.includes("OG_SYNC_CONFLICT.differences(conflict)"),'painel deve usar diferenças determinísticas');
assert.ok(app.includes('Usar versão do servidor'),'opção explícita de servidor ausente');
assert.ok(app.includes('Um checkpoint local será mantido para recuperação.'),'descarte local deve declarar checkpoint');
assert.ok(app.includes('Nada será enviado ao servidor até você confirmar novamente.'),'revisão deve declarar ausência de envio automático');
assert.ok(app.includes("OG_SYNC_BRIDGE.saveReview(review)"),'conciliação preparada deve ficar persistida');
assert.ok(app.includes('Enviar revisão'),'envio conciliado deve exigir ação explícita');
assert.ok(app.includes("if (pendingSyncReview())"),'sync normal deve parar enquanto revisão aguarda confirmação');
assert.ok(app.includes("navigator.serviceWorker.addEventListener('message'"),'app deve receber handoff do service worker');
assert.ok(app.includes("event.data?.type === 'OG_SYNC_OUTBOX_READY'"),'service worker deve delegar flush ao app autenticado');
assert.ok(app.includes("body: JSON.stringify({ leads: state.leads, history: state.history, operations: state.operations, revision: pending.baseRevision })"),'envio conciliado deve usar revisão-base');
assert.ok(app.includes("if (response.status === 409)"),'novo 409 durante envio conciliado deve ser tratado');
assert.ok(!app.includes("sessionStorage.setItem('og_sync_conflict'"),'snapshot completo não deve depender de quota do sessionStorage');
assert.ok(!app.includes("sessionStorage.setItem('og_sync_review_pending'"),'recovery não deve depender do sessionStorage');
assert.ok(!app.includes("if(response.status===409){\n          const remote=await response.json();\n          const merged=OG_DATA_SAFETY.mergeBackup"),'merge/reenvio silencioso antigo ainda presente');
assert.ok(!app.includes("response=await apiFetch('/api/state',{method:'PUT',body:JSON.stringify({...merged,revision:Number(remote.revision||0)})})"),'reenvio automático após 409 ainda presente');
console.log('Sync conflict UI integration tests: PASS');