(()=>{'use strict';
const $=(s,r=document)=>r.querySelector(s),C=()=>globalThis.DUTRA_CORE,A=()=>globalThis.DUTRA_CAPABILITIES;
const toast=m=>typeof globalThis.showToast==='function'?globalThis.showToast(m):console.log('[DUTRA CAP]',m);
const lead=()=>C()?.getSelectedLead?.()||null;
function css(){if($('#dutra-cap-ui-style'))return;const s=document.createElement('style');s.id='dutra-cap-ui-style';s.textContent='.dutraCapBar{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:10px 0 14px}.dutraCapBtn{min-height:58px;border:1px solid #303b44;border-radius:12px;background:#0a1014;color:#eef2f4;font-size:9px;font-weight:900}.dutraCapBtn b{display:block;color:#ffd400}.dutraCapBtn.primary{background:#ffd400;color:#111;border-color:#ffd400}.dutraCapBtn.primary b{color:#111}.dutraCapPanel{position:fixed;inset:0;background:#000b;z-index:290;display:none;align-items:flex-end;justify-content:center}.dutraCapPanel.open{display:flex}.dutraCapSheet{width:min(720px,100%);max-height:86vh;overflow:auto;background:#091015;border:1px solid #3a454e;border-bottom:0;border-radius:20px 20px 0 0;padding:18px}.dutraCapHead{display:flex;justify-content:space-between;align-items:center}.dutraCapForm{display:grid;gap:8px;margin-top:12px}.dutraCapForm input,.dutraCapForm textarea{width:100%;border:1px solid #34404a;border-radius:9px;background:#080d11;color:#fff;padding:10px}.dutraCapForm textarea{min-height:92px}.dutraCapResult{white-space:pre-wrap;border:1px solid #4e4318;border-radius:10px;background:#171609;padding:11px;font-size:10px;line-height:1.5;margin-top:10px}.dutraCapRun{width:100%;height:44px;border:0;border-radius:10px;background:#ffd400;color:#111;font-weight:900;margin-top:9px}@media(max-width:560px){.dutraCapBar{grid-template-columns:1fr}.dutraCapBtn{min-height:50px}}';document.head.appendChild(s)}
function panel(){if($('#dutraCapPanel'))return;document.body.insertAdjacentHTML('beforeend','<div class="dutraCapPanel" id="dutraCapPanel"><div class="dutraCapSheet"><div class="dutraCapHead"><div><small style="color:#ffd400;font-weight:900">DUTRA FORCE</small><h2 id="dutraCapTitle">Inteligência</h2></div><button class="iconBtn" id="dutraCapClose">×</button></div><div class="dutraCapForm" id="dutraCapForm"></div><div class="dutraCapResult" id="dutraCapResult" style="display:none"></div><button class="dutraCapRun" id="dutraCapRun">Executar</button></div></div>');$('#dutraCapClose').onclick=()=>$('#dutraCapPanel').classList.remove('open')}
async function run(name,payload){const box=$('#dutraCapResult');box.style.display='block';box.textContent='Executando…';try{const out=await A().execute(name,payload,{leadId:lead()?.id});box.textContent=typeof out.result==='string'?out.result:JSON.stringify(out.result,null,2)}catch(e){box.textContent='Capacidade ainda não conectada neste ambiente.\n\n'+e.message}}
function open(type){panel();const l=lead();if(!l)return toast('Selecione um cliente.');const f=$('#dutraCapForm'),btn=$('#dutraCapRun');if(type==='research'){ $('#dutraCapTitle').textContent='Pesquisar empresa';f.innerHTML='<input id="capCompany" placeholder="Empresa"><input id="capLocation" placeholder="Cidade / UF"><textarea id="capGoal">Levantar operação, frota, decisores, sinais comerciais e fontes públicas úteis para a próxima abordagem.</textarea>';$('#capCompany').value=l.empresa||l.nome||'';$('#capLocation').value=l.cidadeUf||'';btn.onclick=()=>run('prospect-research',{company:$('#capCompany').value,location:$('#capLocation').value,objective:$('#capGoal').value,leadId:l.id})}else{$('#dutraCapTitle').textContent='Analisar conversa';f.innerHTML='<textarea id="capTranscript" placeholder="Cole aqui a transcrição ou resumo da ligação."></textarea><textarea id="capGoal">Extrair dores, objeções, frota mencionada, compromisso, risco, oportunidade e próxima melhor ação. Não gravar inferências como fatos.</textarea>';btn.onclick=()=>run('call-intelligence',{leadId:l.id,transcript:$('#capTranscript').value,objective:$('#capGoal').value})}$('#dutraCapResult').style.display='none';$('#dutraCapPanel').classList.add('open')}
async function quote(){const l=lead();if(!l)return toast('Selecione um cliente.');try{const contacts=C()?.getState?.()?.operations?.contacts||[],contact=contacts.find(x=>String(x.leadId||x.companyId)===String(l.id))||{};await A().execute('quote',{lead:l,contact,options:{target:'_blank'}},{leadId:l.id})}catch(e){toast(e.message)}}
function render(){css();panel();const p=$('#clients');if(!p)return;let b=$('#dutraClientCapabilities');if(!b){b=document.createElement('div');b.id='dutraClientCapabilities';b.className='dutraCapBar';$('.clientActions',p)?.insertAdjacentElement('afterend',b)}if(!b)return;b.innerHTML='<button class="dutraCapBtn" id="dutraResearch"><b>DUTRA FORCE</b>Pesquisar empresa</button><button class="dutraCapBtn" id="dutraCallIntel"><b>CALL AI</b>Analisar conversa</button><button class="dutraCapBtn primary" id="dutraQuote"><b>COTAÇÃO OFICIAL</b>Cotar este cliente</button>';$('#dutraResearch').onclick=()=>open('research');$('#dutraCallIntel').onclick=()=>open('call');$('#dutraQuote').onclick=quote}
window.addEventListener('dutra:client',render);window.addEventListener('dutra:state',render);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(render,0));else setTimeout(render,0);
})();