(()=>{'use strict';
const clean=v=>String(v??'').trim(), core=()=>globalThis.DUTRA_CORE;
function leadById(id){return core()?.getLeads?.().find(x=>String(x.id)===String(id))||null}
function summary(value){if(typeof value==='string')return clean(value);if(!value||typeof value!=='object')return '';return clean(value.summary||value.note||value.analysis||value.text||value.overview)}
function sources(value){const raw=value?.sources||value?.provenance||value?.references||[];return (Array.isArray(raw)?raw:[raw]).filter(Boolean).map(x=>typeof x==='string'?{label:x,url:''}:{label:clean(x.label||x.title||x.name||x.url),url:clean(x.url||x.href)})}
function suggestion(kind,leadId,result,meta={}){const l=leadById(leadId);if(!l)throw new Error('Cliente não encontrado.');return{id:'SUG-'+Date.now().toString(36).toUpperCase(),kind,leadId:l.id,leadName:l.empresa||l.nome||'',createdAt:new Date().toISOString(),status:'REVIEW_REQUIRED',summary:summary(result),sources:sources(result),result,meta}}
async function commitInteraction(s,options={}){
 const l=leadById(s.leadId);if(!l)throw new Error('Cliente não encontrado.');
 const service=globalThis.OG_INTERACTION_SERVICE;
 const note=clean(options.note||s.summary);if(!note)throw new Error('Revise a nota antes de salvar.');
 if(service?.addInteraction) service.addInteraction(l,{type:options.type||('ai_'+s.kind),note,countAsContact:false,signals:['AI_SUGGESTION_REVIEWED'],objective:'Registro revisado pelo usuário antes de persistir.'});
 else {if(!Array.isArray(l.interactions))l.interactions=[];l.interactions.push({id:'INT-'+Date.now(),at:new Date().toISOString(),type:options.type||('ai_'+s.kind),note,result:'reviewed_ai_suggestion'});}
 if(options.nextAction){if(service?.setNextAction)service.setNextAction(l,options.nextAction,options.followUpAt||'',{reason:options.reason||'Definido após revisão de inteligência assistida.'});else{l.nextAction=options.nextAction;l.followUpAt=options.followUpAt||'';}}
 await core().commit({leads:core().getLeads()},'Inteligência revisada salva no cliente.',{action:'ACCEPT_AI_SUGGESTION',entityType:'lead',entityId:l.id,idempotencyKey:'ai-suggestion:'+s.id,label:'Inteligência revisada'});
 return l;
}
function proposedProfile(s){const r=s?.result||{},src=r.profile||r.fields||r.company||r,out={};for(const k of ['empresa','nome','email','cidadeUf','decisionMaker','pain','accountSummary','sourceLabel'])if(clean(src?.[k]))out[k]=clean(src[k]);if(Number.isFinite(Number(src?.fleetSize))&&Number(src.fleetSize)>=0)out.fleetSize=Number(src.fleetSize);if(Array.isArray(src?.objections))out.objections=src.objections.map(clean).filter(Boolean).slice(0,20);return out}
async function commitProfile(s,fields){const l=leadById(s.leadId);if(!l)throw new Error('Cliente não encontrado.');const allowed=proposedProfile({result:fields||{}}),keys=Object.keys(allowed);if(!keys.length)throw new Error('Nenhum campo aprovado para salvar.');const crm=globalThis.OG_CRM_SERVICE,before=JSON.parse(JSON.stringify(l)),updated=crm?.updateLeadProfile?crm.updateLeadProfile(l,allowed):Object.assign({},l,allowed);Object.keys(l).forEach(k=>delete l[k]);Object.assign(l,updated);const changed=crm?.diffProfile?crm.diffProfile(before,l):keys,refs=(s.sources||[]).map(x=>x.url||x.label).filter(Boolean).join(' | '),note='Campos revisados: '+changed.join(', ')+(refs?' · Fontes: '+refs:'');globalThis.OG_INTERACTION_SERVICE?.addInteraction?.(l,{type:'ai_research_profile_reviewed',note,countAsContact:false,signals:['AI_SUGGESTION_REVIEWED','SOURCE_PRESERVED'],objective:'Atualização estruturada aprovada pelo usuário.'});await core().commit({leads:core().getLeads()},'Campos revisados salvos no cliente.',{action:'ACCEPT_AI_PROFILE_FIELDS',entityType:'lead',entityId:l.id,idempotencyKey:'ai-profile:'+s.id,label:'Perfil revisado'});return{lead:l,changed}}
function proposedCall(s){const r=s?.result||{},src=r.call||r.analysis||r,out={};const one=(k,...aliases)=>{for(const a of [k,...aliases])if(clean(src?.[a])){out[k]=clean(src[a]);break}};one('pain','dor','painPoint');one('commitment','compromisso');one('nextAction','next_action','proximaAcao');one('reason','nextActionReason','motivo');one('objective','nextActionObjective','objetivo');one('expectedResult','nextActionExpectedResult','resultadoEsperado');one('followUpAt','follow_up_at','followUp');if(Array.isArray(src?.objections))out.objections=src.objections.map(clean).filter(Boolean).slice(0,20);return out}
async function commitCall(s,approved={}){const l=leadById(s.leadId);if(!l)throw new Error('Cliente não encontrado.');const a=proposedCall({result:approved}),service=globalThis.OG_INTERACTION_SERVICE,parts=[];if(a.pain)parts.push('Dor: '+a.pain);if(a.objections?.length)parts.push('Objeções: '+a.objections.join('; '));if(a.commitment)parts.push('Compromisso: '+a.commitment);if(!parts.length&&!a.nextAction)throw new Error('Nenhuma informação da ligação foi aprovada.');if(parts.length){service?.addInteraction?.(l,{type:'ai_call_reviewed',note:parts.join(' · '),countAsContact:false,signals:['AI_SUGGESTION_REVIEWED'],objective:'Análise de ligação revisada pelo usuário.'});if(a.pain)l.pain=a.pain;if(a.objections?.length)l.objections=a.objections}if(a.nextAction){if(service?.setNextAction)service.setNextAction(l,a.nextAction,a.followUpAt||'',{reason:a.reason||'Definido após revisão da ligação.',objective:a.objective||'',expectedResult:a.expectedResult||''});else{l.nextAction=a.nextAction;l.followUpAt=a.followUpAt||'';l.nextActionReason=a.reason||'';l.nextActionObjective=a.objective||'';l.nextActionExpectedResult=a.expectedResult||''}}await core().commit({leads:core().getLeads()},'Ligação revisada salva no cliente.',{action:'ACCEPT_CALL_AI_REVIEW',entityType:'lead',entityId:l.id,idempotencyKey:'call-ai:'+s.id,label:'Call AI revisada'});return l}
globalThis.DUTRA_REVIEW_GATE=Object.freeze({fromResearch:(leadId,result,meta)=>suggestion('research',leadId,result,meta),fromCall:(leadId,result,meta)=>suggestion('call',leadId,result,meta),proposedProfile,proposedCall,commitInteraction,commitProfile,commitCall});
})();